"Pre-Test":
  stage: test
  rules:
    - !reference [.push-or-merge-to-protected, rules]
  image:
    name: node:20.11-alpine3.19
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules

"Check Lint":
  stage: test
  needs:
    - Pre-Test
  rules:
    - !reference [.push-or-merge-to-protected, rules]
  image:
    name: node:20.11-alpine3.19
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn lint

"Test Coverage":
  stage: test
  needs:
    - Pre-Test
  rules:
    - !reference [.push-or-merge-to-protected, rules]
  image:
    name: node:20.11-alpine3.19
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: test-results/coverage/cobertura-coverage.xml
      junit:
        - test-results/junit.xml
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn test:cov
