// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz_eI9JGaDY_S-w2lEu9DGEY_w4s7bw6U',
    appId: '1:1065587563292:web:5d5ebb91fa45aab346b8d9',
    messagingSenderId: '1065587563292',
    projectId: 'luyen-thi-gplx-c3b7f',
    authDomain: 'luyen-thi-gplx-c3b7f.firebaseapp.com',
    storageBucket: 'luyen-thi-gplx-c3b7f.firebasestorage.app',
    measurementId: 'G-3EFY27R5MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNFAf0jmQvOIfK4gKbRjK4c3Q-dN9rxE',
    appId: '1:1065587563292:android:b43aa2f303db69bc46b8d9',
    messagingSenderId: '1065587563292',
    projectId: 'luyen-thi-gplx-c3b7f',
    databaseURL: 'https://luyen-thi-gplx-c3b7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'luyen-thi-gplx-c3b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6YcmtFpO5a0oGhHDPGw5qrtinBqtNFBU',
    appId: '1:1065587563292:ios:137ead8135b487ac46b8d9',
    messagingSenderId: '1065587563292',
    projectId: 'luyen-thi-gplx-c3b7f',
    databaseURL: 'https://luyen-thi-gplx-c3b7f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'luyen-thi-gplx-c3b7f.firebasestorage.app',
    iosBundleId: 'com.example.gplx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6YcmtFpO5a0oGhHDPGw5qrtinBqtNFBU',
    appId: '1:1065587563292:ios:137ead8135b487ac46b8d9',
    messagingSenderId: '1065587563292',
    projectId: 'luyen-thi-gplx-c3b7f',
    storageBucket: 'luyen-thi-gplx-c3b7f.firebasestorage.app',
    iosBundleId: 'com.example.gplx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz_eI9JGaDY_S-w2lEu9DGEY_w4s7bw6U',
    appId: '1:1065587563292:web:a13b85d564d6bc7c46b8d9',
    messagingSenderId: '1065587563292',
    projectId: 'luyen-thi-gplx-c3b7f',
    authDomain: 'luyen-thi-gplx-c3b7f.firebaseapp.com',
    storageBucket: 'luyen-thi-gplx-c3b7f.firebasestorage.app',
    measurementId: 'G-RNK7G896MZ',
  );
}