name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2" # Specify the exact Flutter version
      - run: flutter pub get
      - run: dart pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter analyze
      # - run: flutter build apk --release
