name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2" # Specify the exact Flutter version

      - run: make init
      - run: flutter test
      - run: flutter analyze
      # - run: flutter build apk --release
